### ISSUE TITLE
sanCarloSquare.png is missing?

### ISSUE THREAD

**Issue by KNtronov** [kelvin-olaiya/SanCarloSquareStampede#116]
Good Day,

I think that sanCarloSquare.png referenced in the simulation.yml is missing from the project. This breaks the simulation. Could you please include it in the project?

**Comment by kelvin-olaiya** [comment]
Hi!
Sorry for the delay, I've added the missing png. 
The simulation should now run correctly. I wonder how I didn't notice this before... 🤔 
In any case, thank you for signaling 🙏🏾
